package org.acme.employeescheduling.rest;

import java.util.HashSet;
import org.acme.employeescheduling.domain.Demand;

import java.util.List;
import org.acme.employeescheduling.domain.Resource;

public class StaticDataProvider {

    public static List<Resource> RESOURCES = List.of(
        new Resource("Abbie Birthday", "Begleiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_2"),
        new Resource("Abe Rudder", "Begleiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_3"),
        new Resource("Abel N. Willan", "Begleiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_1"),
        new Resource("Al B. Tross", "Begleiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_2"),
        new Resource("Al B. Zienya", "Begleiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_3"),
        new Resource("Al Dente", "Begleiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_1"),
        new Resource("Al Fresco", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_1"),
        new Resource("Al Gore Rythim", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_2"),
        new Resource("Al K. Seltzer", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_3"),
        new Resource("Al Kaholic", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_1"),
        new Resource("Al Kaseltzer", "Pollier", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_1"),
        new Resource("Al Luminum", "Sicherheitschef/in", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_1"),
        new Resource("Al Nino", "Sicherheitschef/in", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_2"),
        new Resource("Al O'Moaney", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_1"),
        new Resource("Alec Tricity", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_1"),
        new Resource("Alex Blaine Layder", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_2"),
        new Resource("Alf A. Romeo", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_2"),
        new Resource("Alf Abet", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_3"),
        new Resource("Ali Gaither", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_3"),
        new Resource("Ali Gator", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_1"),
        new Resource("Ali Katt", "Vorarbeiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_3"),
        new Resource("Allen Rench", "Vorarbeiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_2"),
        new Resource("Amanda B. Reckonwith", "Vorarbeiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "FR_3"),
        new Resource("Amanda Lynn", "Begleiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_3"),
        new Resource("Andy Friese", "Begleiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_4"),
        new Resource("Andy Gravity", "Begleiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_2"),
        new Resource("Andy Structible", "Begleiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_3"),
        new Resource("Anita Bath", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_1"),
        new Resource("Anita Bathe", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_1"),
        new Resource("Anita Job", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_1"),
        new Resource("Anita Knapp", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_2"),
        new Resource("Ann B. Dextrous", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_2"),
        new Resource("Ann Chovie", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_2"),
        new Resource("Ann Tartica", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_3"),
        new Resource("Anna Conda", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_3"),
        new Resource("Anna Graham", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_3"),
        new Resource("Anna Mull", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_4"),
        new Resource("Anna Prentice", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_4"),
        new Resource("Anna Sasin", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_4"),
        new Resource("Anna Septic", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_1"),
        new Resource("Anne T. Lope", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_2"),
        new Resource("Anne Teak", "Pollier", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_3"),
        new Resource("Anne Ville", "Pollier", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_4"),
        new Resource("Annette Curtain", "Pollier", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_1"),
        new Resource("Annie Buddyhome", "Sicherheitschef/in", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_1"),
        new Resource("Annie Howe", "Sicherheitschef/in", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_2"),
        new Resource("Annie Matter", "Sicherheitschef/in", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_3"),
        new Resource("Annie Moore", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_1"),
        new Resource("April Schauer", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_2"),
        new Resource("Arch N. Emmy", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_3"),
        new Resource("Aretha Holly", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_4"),
        new Resource("Ariel Hassle", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_1"),
        new Resource("Barry Cade", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_2"),
        new Resource("Barry D'Alive", "Vorarbeiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_4"),
        new Resource("Barry D. Hatchett", "Vorarbeiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "REN_4"),
        new Resource("Barry Shmelly", "Begleiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_2"),
        new Resource("Bart Ender", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_1"),
        new Resource("Bea Lowe", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_1"),
        new Resource("Bea Minor", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_1"),
        new Resource("Bea Sting", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_2"),
        new Resource("Beau Tye", "Gleismonteur", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_2"),
        new Resource("Beau Vine", "Pollier", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_1"),
        new Resource("Ben Crobbery", "Pollier", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_1"),
        new Resource("Ben D. Fender", "Pollier", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_2"),
        new Resource("Ben Dover", "Sicherheitschef/in", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_1"),
        new Resource("Ben Down", "Sicherheitschef/in", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_2"),
        new Resource("Ben Lyon", "Sicherheitschef/in", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_1"),
        new Resource("Ben Thair", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_1"),
        new Resource("Bertha D. Blues", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_1"),
        new Resource("Bess Eaton", "TFF", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_2"),
        new Resource("Bess Twishes", "Vorarbeiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_2"),
        new Resource("Biff Wellington", "Vorarbeiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_2"),
        new Resource("Bill Board", "Vorarbeiter", new HashSet<>(), new HashSet<>(), new HashSet<>(), "YV_2"));

    public static List<String> getResourceCategories() {
        return new DemandDataProvider().readDemands().stream().map(Demand::getRequiredResourceCategory).toList();
//        return List.of(
//            "Arbeitsleiter/in",
//            "Arbeitsstellenkoordinator/in",
//            "Basistechniker/in",
//            "Basistechniker/in SAI",
//            "Begleiter/in",
//            "Chefmonteur/in",
//            "Chefmonteur/in BST",
//            "Chefmonteur/in SAA",
//            "Cheftechniker/in",
//            "Cheftechniker/in SAI",
//            "Facharbeiter/in extern",
//            "Geomatiker/in",
//            "Gleismonteur/in",
//            "Gleismonteur/in komplex",
//            "Handwerker/in",
//            "Handwerker/in SAA",
//            "Hilfsarbeiter/in extern",
//            "Kranführer/in",
//            "Lernende/r",
//            "Monteur/in",
//            "Monteur/in KLU SAA",
//            "Polier/in",
//            "Sicherheitschef/in",
//            "Sicherheitsleiter/in",
//            "Sicherheitswärter/in",
//            "Spezialhandwerker/in",
//            "Spezialmonteur/in",
//            "Spezialmonteur/in BST",
//            "Spezialmonteur/in SAA",
//            "Spitzenlast temporär",
//            "TFF",
//            "Teamleiter/in",
//            "Techniker/in",
//            "Techniker/in SAI",
//            "Techniker/in spezial",
//            "Techniker/in spezial SAI",
//            "Verdrahter/in extern",
//            "Vermessungsassistent/in",
//            "Vorarbeiter/in"
//        );
    }

    public static List<String> getQualifications() {
        return new DemandDataProvider().readDemands().stream().flatMap(demand -> demand.getRequiredQualifications().stream()).toList();
//        return List.of(
//            "Bauleiter",
//            "Güterzugsmodul",
//            "Quereinsteiger",
//            "Am 843 SBB",
//            "Gefahrstoff INFRA WK",
//            "Triebfahrzeugführende A / PP",
//            "XTm Bendini",
//            "Rangierbegleitende Ai40 / PP",
//            "Selbstschutz Arbeiten WK",
//            "Triebfahrzeugführende Art. 10b / PP",
//            "Italienisch",
//            "Sicherheitschef/in WK",
//            "Zugbegleitende Bi / PP",
//            "Tmf 232",
//            "Fallschutz Höhensicherung",
//            "Gefahrgut WK TFF und Begleiter Bau",
//            "Kirow 100",
//            "Triebfahrzeugführende B100 / PP",
//            "Tm 232 Cargo",
//            "Schienentransporteinheit elektrisch",
//            "Arbeitsstellenkoordinator",
//            "Tm 234",
//            "Aem 940",
//            "Zertifizierung Neutralisation",
//            "Sicherheitswärter/in WK",
//            "Tm 232",
//            "Rangierbegleitende Ai / PP",
//            "Niederflurwagen Xaas (NT)",
//            "SUVA Kranausbildung Kat. A WK",
//            "Am 841",
//            "Instruktion TUBEMO",
//            "Tm 234-4",
//            "Schalten und Erden WK",
//            "Schienentransporteinheit mechanisch",
//            "ETCS L1",
//            "Netz SBB",
//            "Minimel Lynx Bediener",
//            "Triebfahrzeugführende A40 / PP",
//            "Arb. mit Motorsägen Kanthölzern MOSÄ1",
//            "ETCS",
//            "Instruierter Mitarbeiter RSS",
//            "Anschlagen von Lasten"
//        );
    }
}
