@startuml
'https://plantuml.com/class-diagram

class Mitarbeiter {
  +String id
  +String resourceCategory
  +String division
  +String[] qualifikationen
  +Date[] abwesenheiten
}

class Baustelle {
  +String id
  +Bedarf[] bedarfe
  +DateTime startZeit
  +DateTime endZeit
}

class Bedarf {
  +String resourceCategory
  +String[] qualifikation
  +DateTime startZeit
  +DateTime endZeit
}

@enduml