@startuml
'https://plantuml.com/class-diagram

class Worker {
  +String id
  +String resourceCategory
  +String division
  +String[] qualification
  +Date[] freeDays
}

class Baustelle {
  +String id
  +Bedarf[] demands
  +DateTime startTime
  +DateTime endTime
}

class Demand {
  +String resourceCategory
  +String[] qualifications
  +DateTime startTime
  +DateTime endTime
}

@enduml